# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sportsbite
tagline:             'Developer Project Built with Lanyon'
description:         'A news dissemination engine <a href="http://jekyllrb.com" target="_blank">Jekyll</a> that focuses on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://sportsbite-news.github.io
baseurl:             'sportsbite.news'
paginate:            5

# About/contact
author:
  name:              Waker Mahmud
  url:               https://twitter.com/digideskio
  email:             admin@sportsbite.news

# Custom vars
version:             0.0.1
